// src/pages/admin/Login.tsx
import { useState } from "react";
import { Card, Form, Input, Button, Message } from "@arco-design/web-react";
import { IconUser, IconLock } from "@arco-design/web-react/icon";
import { useNavigate } from "react-router-dom";
import { useIsMobile } from "@/hooks/useIsMobile";

const FormItem = Form.Item;

export default function AdminLogin() {
  const navigate = useNavigate();
  const isMobile = useIsMobile();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState<{ username: string; password: string }>({
    username: "admin",
    password: "admin123",
  });

  const handleFinish = () => {
    if (!formData.username) {
      Message.warning("请输入账号");
      return;
    }
    if (!formData.password) {
      Message.warning("请输入密码");
      return;
    }
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      if (formData.username === "admin" && formData.password === "admin123") {
        localStorage.setItem("admin_auth", "1");
        Message.success("登录成功");
        navigate("/admin/dashboard", { replace: true });
      } else {
        Message.error("账号或密码错误");
      }
    }, 500);
  };

  return (
    <div
      style={{
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "linear-gradient(135deg, #16a34a 0%, #15803d 100%)",
        padding: 16,
      }}
    >
      <Card
        style={{ width: "100%", maxWidth: 380, boxShadow: "0 8px 24px rgba(0,0,0,0.15)", padding: isMobile ? "24px 16px" : "32px 28px", boxSizing: "border-box" }}
        bordered
      >
        <div style={{ textAlign: "center", marginBottom: 24 }}>
          <h3 style={{ marginBottom: 4, color: "rgb(var(--primary-6))", marginTop: 0 }}>
            商场考勤管理系统
          </h3>
          <span style={{ color: "#999" }}>管理后台 · v1.0</span>
        </div>
        <Form
          layout="vertical"
          onSubmit={(e) => {
            e.preventDefault();
            handleFinish();
          }}
        >
          <FormItem label="账号">
            <Input
              value={formData.username}
              onChange={(value) =>
                setFormData({ ...formData, username: value })
              }
              placeholder="账号"
              prefix={<IconUser />}
              allowClear
            />
          </FormItem>
          <FormItem label="密码">
            <Input.Password
              value={formData.password}
              onChange={(value) =>
                setFormData({ ...formData, password: value })
              }
              placeholder="密码"
              prefix={<IconLock />}
              allowClear
            />
          </FormItem>
          <FormItem style={{ marginBottom: 0 }}>
            <Button
              type="primary"
              long
              loading={loading}
              onClick={handleFinish}
            >
              登 录
            </Button>
          </FormItem>
        </Form>
        <div style={{ marginTop: 16, textAlign: "center" }}>
          <span style={{ color: "#999", fontSize: 12 }}>
            默认账号：admin / admin123
          </span>
        </div>
      </Card>
    </div>
  );
}

// src/views/login/index.vue
<script setup lang="ts">
import { reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { Message } from '@arco-design/web-vue';
import type { FieldData } from '@arco-design/web-vue';

const router = useRouter();
const route = useRoute();
const loading = ref(false);

const form = reactive({
  username: 'admin',
  password: 'admin123',
});

const rules = {
  username: [{ required: true, message: '请输入用户名' }],
  password: [{ required: true, message: '请输入密码' }],
};

function handleSubmit(values: FieldData | undefined, errors: unknown) {
  if (errors) return;
  loading.value = true;
  setTimeout(() => {
    if (form.username === 'admin' && form.password === 'admin123') {
      localStorage.setItem('admin_auth', '1');
      Message.success('登录成功');
      const redirect = (route.query.redirect as string) || '/admin/dashboard';
      router.push(redirect);
    } else {
      Message.error('用户名或密码错误');
    }
    loading.value = false;
  }, 400);
}
</script>

<template>
  <div class="login-page">
    <div class="login-card">
      <div class="login-header">
        <div class="logo-badge">考勤</div>
        <h1>商场考勤管理系统</h1>
        <p>管理员登录</p>
      </div>
      <a-form :model="form" :rules="rules" layout="vertical" @submit="handleSubmit">
        <a-form-item field="username" label="用户名">
          <a-input v-model="form.username" placeholder="请输入用户名" allow-clear />
        </a-form-item>
        <a-form-item field="password" label="密码">
          <a-input-password v-model="form.password" placeholder="请输入密码" allow-clear />
        </a-form-item>
        <a-form-item>
          <a-button type="primary" html-type="submit" long :loading="loading" size="large">
            登录
          </a-button>
        </a-form-item>
      </a-form>
      <div class="login-tip">默认账号：admin / admin123</div>
    </div>
  </div>
</template>

<style scoped>
.login-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #e8f3ff 0%, #f5f7fa 100%);
  padding: 16px;
}

.login-card {
  width: 100%;
  max-width: 380px;
  background: var(--color-bg-1);
  border-radius: 12px;
  padding: 40px 32px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.08);
}

.login-header {
  text-align: center;
  margin-bottom: 32px;
}

.logo-badge {
  width: 64px;
  height: 64px;
  margin: 0 auto 16px;
  background: rgb(var(--primary-6));
  color: #fff;
  border-radius: 16px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 20px;
  font-weight: 700;
}

.login-header h1 {
  font-size: 22px;
  font-weight: 600;
  margin: 0 0 4px;
  color: var(--color-text-1);
}

.login-header p {
  font-size: 13px;
  color: var(--color-text-3);
  margin: 0;
}

.login-tip {
  text-align: center;
  font-size: 12px;
  color: var(--color-text-3);
  margin-top: 12px;
}
</style>
