// src/views/analysis/index.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { Message } from '@arco-design/web-vue';
import type { TableColumnData } from '@arco-design/web-vue';
import dayjs from 'dayjs';
import { useAdminStore } from '@/store/admin';
import { exportCsv } from '@/utils/exportCsv';
import VChartView from '@/components/VChartView.vue';
import type { AttendanceRecord } from '@/types';

const store = useAdminStore();

onMounted(() => {
  if (!store.merchants.length || !store.records.length) {
    store.loadFromApi();
  }
});

// ===== 粒度与日期选择 =====
type Granularity = 'day' | 'week' | 'month' | 'quarter' | 'year';
const granularity = ref<Granularity>('month');

const granularityOptions = [
  { label: '日', value: 'day' },
  { label: '周', value: 'week' },
  { label: '月', value: 'month' },
  { label: '季', value: 'quarter' },
  { label: '年', value: 'year' },
];

// 单日使用 DatePicker，其余使用 RangePicker
const baseDate = ref<string>(dayjs().subtract(1, 'day').format('YYYY-MM-DD'));
const compareDate = ref<string>(dayjs().format('YYYY-MM-DD'));
const baseRange = ref<string[]>([
  dayjs().subtract(1, 'month').startOf('month').format('YYYY-MM-DD'),
  dayjs().subtract(1, 'month').endOf('month').format('YYYY-MM-DD'),
]);
const compareRange = ref<string[]>([
  dayjs().startOf('month').format('YYYY-MM-DD'),
  dayjs().endOf('month').format('YYYY-MM-DD'),
]);

function quarterStart(d: dayjs.Dayjs): dayjs.Dayjs {
  const qStart = Math.floor(d.month() / 3) * 3;
  return d.month(qStart).startOf('month');
}

// 切换粒度时设置合理的默认区间
watch(granularity, (g) => {
  const today = dayjs();
  if (g === 'day') {
    baseDate.value = today.subtract(1, 'day').format('YYYY-MM-DD');
    compareDate.value = today.format('YYYY-MM-DD');
    return;
  }
  let baseS: dayjs.Dayjs;
  let baseE: dayjs.Dayjs;
  let cmpS: dayjs.Dayjs;
  let cmpE: dayjs.Dayjs;
  switch (g) {
    case 'week':
      cmpS = today.startOf('week');
      cmpE = today.endOf('week');
      baseS = cmpS.subtract(1, 'week');
      baseE = cmpE.subtract(1, 'week');
      break;
    case 'month':
      cmpS = today.startOf('month');
      cmpE = today.endOf('month');
      baseS = cmpS.subtract(1, 'month');
      baseE = cmpE.subtract(1, 'month');
      break;
    case 'quarter':
      cmpS = quarterStart(today);
      cmpE = cmpS.add(2, 'month').endOf('month');
      baseS = cmpS.subtract(3, 'month');
      baseE = cmpE.subtract(3, 'month');
      break;
    case 'year':
      cmpS = today.startOf('year');
      cmpE = today.endOf('year');
      baseS = cmpS.subtract(1, 'year');
      baseE = cmpE.subtract(1, 'year');
      break;
  }
  baseRange.value = [baseS!.format('YYYY-MM-DD'), baseE!.format('YYYY-MM-DD')];
  compareRange.value = [cmpS!.format('YYYY-MM-DD'), cmpE!.format('YYYY-MM-DD')];
});

const baseStart = computed(() =>
  granularity.value === 'day' ? baseDate.value : baseRange.value?.[0] ?? ''
);
const baseEnd = computed(() =>
  granularity.value === 'day' ? baseDate.value : baseRange.value?.[1] ?? ''
);
const compareStart = computed(() =>
  granularity.value === 'day' ? compareDate.value : compareRange.value?.[0] ?? ''
);
const compareEnd = computed(() =>
  granularity.value === 'day' ? compareDate.value : compareRange.value?.[1] ?? ''
);

// ===== 比率计算 =====
function recordsInRange(start: string, end: string): AttendanceRecord[] {
  if (!start || !end) return [];
  return store.records.filter((r) => r.date >= start && r.date <= end);
}

function rateOf(recs: AttendanceRecord[]): number {
  if (!recs.length) return 0;
  const signedIn = recs.filter((r) => r.status === 'signedIn').length;
  return Math.round((signedIn / recs.length) * 1000) / 10;
}

const baseRecords = computed(() => recordsInRange(baseStart.value, baseEnd.value));
const compareRecords = computed(() => recordsInRange(compareStart.value, compareEnd.value));

const baseRate = computed(() => rateOf(baseRecords.value));
const compareRate = computed(() => rateOf(compareRecords.value));
const diffRate = computed(() => Math.round((compareRate.value - baseRate.value) * 10) / 10);
const growthRate = computed(() => {
  if (baseRate.value === 0) return 0;
  return Math.round(((compareRate.value - baseRate.value) / baseRate.value) * 1000) / 10;
});

function fmtSigned(v: number) {
  return `${v > 0 ? '+' : ''}${v}`;
}

// ===== 趋势对比：每日到岗率，按序号对齐 =====
function dailyRates(recs: AttendanceRecord[]): number[] {
  const byDate = new Map<string, AttendanceRecord[]>();
  recs.forEach((r) => {
    const arr = byDate.get(r.date) ?? [];
    arr.push(r);
    byDate.set(r.date, arr);
  });
  return Array.from(byDate.keys())
    .sort()
    .map((d) => rateOf(byDate.get(d)!));
}

const trendSpec = computed(() => {
  const baseDays = dailyRates(baseRecords.value);
  const compareDays = dailyRates(compareRecords.value);
  const maxLen = Math.max(baseDays.length, compareDays.length);
  const values: { idx: string; type: string; value: number }[] = [];
  for (let i = 0; i < maxLen; i++) {
    const label = `第${i + 1}天`;
    values.push({ idx: label, type: '基期', value: baseDays[i] ?? 0 });
    values.push({ idx: label, type: '对比期', value: compareDays[i] ?? 0 });
  }
  return {
    type: 'area',
    data: [{ id: 'trend', values }],
    series: [
      {
        type: 'area',
        xField: 'idx',
        yField: 'value',
        seriesField: 'type',
        area: { style: { fillOpacity: 0.25 } },
        line: { style: { lineWidth: 2 } },
      },
    ],
    axes: [
      { orient: 'bottom', type: 'band' },
      { orient: 'left', type: 'linear', title: { visible: true, text: '到岗率(%)' } },
    ],
    legends: { visible: true, position: 'top' },
    tooltip: { visible: true },
  };
});

// ===== 楼层对比 =====
const floorSpec = computed(() => {
  const floors = Array.from(new Set(store.merchants.map((m) => m.floor))).filter(Boolean).sort();
  const values: { floor: string; type: string; value: number }[] = [];
  floors.forEach((f) => {
    const mids = store.merchants.filter((m) => m.floor === f).map((m) => m.id);
    const base = baseRecords.value.filter((r) => mids.includes(r.merchantId));
    const comp = compareRecords.value.filter((r) => mids.includes(r.merchantId));
    values.push({ floor: f, type: '基期', value: rateOf(base) });
    values.push({ floor: f, type: '对比期', value: rateOf(comp) });
  });
  return {
    type: 'bar',
    data: [{ id: 'floor', values }],
    series: [{ type: 'bar', xField: 'floor', yField: 'value', seriesField: 'type' }],
    axes: [
      { orient: 'bottom', type: 'band' },
      { orient: 'left', type: 'linear', title: { visible: true, text: '到岗率(%)' } },
    ],
    legends: { visible: true, position: 'top' },
    tooltip: { visible: true },
  };
});

// ===== 异常商户明细表 =====
interface AbnormalRow {
  merchantId: string;
  name: string;
  floor: string;
  baseRate: number;
  compareRate: number;
  diff: number;
}

const abnormalRows = computed<AbnormalRow[]>(() => {
  const rows: AbnormalRow[] = [];
  store.merchants.forEach((m) => {
    const base = baseRecords.value.filter((r) => r.merchantId === m.id);
    const comp = compareRecords.value.filter((r) => r.merchantId === m.id);
    if (!base.length && !comp.length) return;
    const br = rateOf(base);
    const cr = rateOf(comp);
    const diff = Math.round((cr - br) * 10) / 10;
    if (Math.abs(diff) > 10) {
      rows.push({
        merchantId: m.id,
        name: m.name,
        floor: m.floor,
        baseRate: br,
        compareRate: cr,
        diff,
      });
    }
  });
  return rows.sort((a, b) => Math.abs(b.diff) - Math.abs(a.diff));
});

const columns: TableColumnData[] = [
  { title: '商户', dataIndex: 'name' },
  { title: '楼层', dataIndex: 'floor', width: 80, align: 'center' },
  { title: '基期率(%)', dataIndex: 'baseRate', width: 110, align: 'right' },
  { title: '对比期率(%)', dataIndex: 'compareRate', width: 120, align: 'right' },
  { title: '差异(%)', slotName: 'diff', width: 110, align: 'right' },
  { title: '操作', slotName: 'operation', width: 120, fixed: 'right' },
];

function diffColor(diff: number) {
  return diff > 0 ? 'green' : diff < 0 ? 'red' : '';
}

function handleExport() {
  if (!abnormalRows.value.length) {
    Message.warning('暂无可导出的数据');
    return;
  }
  exportCsv(
    `深度分析-异常商户-${dayjs().format('YYYYMMDD')}`,
    abnormalRows.value.map((r) => ({
      商户: r.name,
      楼层: r.floor,
      基期率: r.baseRate,
      对比期率: r.compareRate,
      差异: r.diff,
    }))
  );
  Message.success('已导出');
}

function handleExportRow(row: AbnormalRow) {
  const recs = store.records.filter(
    (r) =>
      r.merchantId === row.merchantId &&
      ((r.date >= baseStart.value && r.date <= baseEnd.value) ||
        (r.date >= compareStart.value && r.date <= compareEnd.value))
  );
  exportCsv(
    `深度分析-${row.name}-${dayjs().format('YYYYMMDD')}`,
    recs.map((r) => ({
      日期: r.date,
      状态: r.status === 'signedIn' ? '已到岗' : r.status === 'absent' ? '缺勤' : '未签到',
      签到时间: r.signedAt ?? '',
      操作人: r.operator ?? '',
      备注: r.remark ?? '',
    }))
  );
  Message.success('已导出该商户明细');
}
</script>

<template>
  <div class="page-container">
    <!-- 顶部条件选择 -->
    <a-card style="margin-bottom: 16px">
      <a-space wrap :size="12">
        <span class="control-label">粒度</span>
        <a-radio-group v-model="granularity" type="button" size="small">
          <a-radio v-for="o in granularityOptions" :key="o.value" :value="o.value">{{ o.label }}</a-radio>
        </a-radio-group>

        <span class="control-label">基期</span>
        <a-date-picker
          v-if="granularity === 'day'"
          v-model="baseDate"
          value-format="YYYY-MM-DD"
          format="YYYY-MM-DD"
          style="width: 160px"
        />
        <a-range-picker
          v-else
          v-model="baseRange"
          value-format="YYYY-MM-DD"
          format="YYYY-MM-DD"
          style="width: 280px"
          :placeholder="['开始日期', '结束日期']"
        />

        <span class="control-label">对比期</span>
        <a-date-picker
          v-if="granularity === 'day'"
          v-model="compareDate"
          value-format="YYYY-MM-DD"
          format="YYYY-MM-DD"
          style="width: 160px"
        />
        <a-range-picker
          v-else
          v-model="compareRange"
          value-format="YYYY-MM-DD"
          format="YYYY-MM-DD"
          style="width: 280px"
          :placeholder="['开始日期', '结束日期']"
        />
      </a-space>
    </a-card>

    <!-- 统计卡 -->
    <a-grid :cols="{ xs: 2, sm: 4 }" :col-gap="12" :row-gap="12" style="margin-bottom: 16px">
      <a-grid-item>
        <a-card>
          <div class="stat-card-value">{{ baseRate }}%</div>
          <div class="stat-card-label">基期到岗率</div>
        </a-card>
      </a-grid-item>
      <a-grid-item>
        <a-card>
          <div class="stat-card-value">{{ compareRate }}%</div>
          <div class="stat-card-label">对比期到岗率</div>
        </a-card>
      </a-grid-item>
      <a-grid-item>
        <a-card>
          <div
            class="stat-card-value"
            :style="{ color: diffRate > 0 ? 'rgb(var(--green-6))' : diffRate < 0 ? 'rgb(var(--red-6))' : '' }"
          >
            {{ fmtSigned(diffRate) }}%
          </div>
          <div class="stat-card-label">同比差值</div>
        </a-card>
      </a-grid-item>
      <a-grid-item>
        <a-card>
          <div
            class="stat-card-value"
            :style="{ color: growthRate > 0 ? 'rgb(var(--green-6))' : growthRate < 0 ? 'rgb(var(--red-6))' : '' }"
          >
            {{ fmtSigned(growthRate) }}%
          </div>
          <div class="stat-card-label">环比增长率</div>
        </a-card>
      </a-grid-item>
    </a-grid>

    <!-- 图表对比 -->
    <a-grid :cols="{ xs: 1, lg: 2 }" :col-gap="12" :row-gap="12" style="margin-bottom: 16px">
      <a-grid-item>
        <a-card title="趋势对比 — 每日到岗率">
          <div style="height: 320px"><VChartView :spec="trendSpec" /></div>
        </a-card>
      </a-grid-item>
      <a-grid-item>
        <a-card title="楼层对比 — 基期 vs 对比期">
          <div style="height: 320px"><VChartView :spec="floorSpec" /></div>
        </a-card>
      </a-grid-item>
    </a-grid>

    <!-- 异常商户明细表 -->
    <a-card title="异常商户明细（到岗率差异 > 10%）">
      <div class="toolbar">
        <span class="text-secondary">共 {{ abnormalRows.length }} 家异常商户</span>
        <a-button type="primary" @click="handleExport">
          <template #icon><icon-download /></template>
          导出 CSV
        </a-button>
      </div>
      <a-table
        :data="abnormalRows"
        :columns="columns"
        :pagination="{ pageSize: 10, showTotal: true }"
        :loading="store.loading"
        row-key="merchantId"
        size="medium"
        :scroll="{ x: 800 }"
      >
        <template #diff="{ record }">
          <a-tag :color="diffColor(record.diff)">{{ fmtSigned(record.diff) }}%</a-tag>
        </template>
        <template #operation="{ record }">
          <a-button type="text" size="small" @click="handleExportRow(record)">导出明细</a-button>
        </template>
      </a-table>
    </a-card>
  </div>
</template>

<style scoped>
.control-label {
  color: var(--color-text-3);
  font-size: 13px;
}
.toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
}
.text-secondary {
  color: var(--color-text-3);
  font-size: 13px;
}
</style>

// src/pages/admin/Analysis.tsx
import { useMemo, useState, useEffect, useRef } from "react";
import {
  Card,
  Radio,
  DatePicker,
  Button,
  Statistic,
  Table,
  Tag,
  Message,
} from "@arco-design/web-react";
import VChart from "@visactor/vchart";
import dayjs, { type Dayjs } from "dayjs";
import { useAdminStore } from "@/store/useAdminStore";
import { exportCsv } from "@/utils/exportCsv";

/* VChart 图表组件 */
function VChartComponent({ spec }: { spec: any }) {
  const divRef = useRef<HTMLDivElement>(null);
  const chartRef = useRef<any>(null);

  useEffect(() => {
    if (!divRef.current) return;
    const chart = new VChart(spec, { dom: divRef.current });
    chartRef.current = chart;
    chart.renderSync();
    return () => {
      chartRef.current?.release();
      chartRef.current = null;
    };
  }, [JSON.stringify(spec)]);

  return <div ref={divRef} style={{ width: "100%", height: "100%" }} />;
}

/* 内联 SVG 图标 */
const Ic = ({ d, size = 18, style }: { d: string; size?: number; style?: React.CSSProperties }) => (
  <svg viewBox="0 0 24 24" width={size} height={size} fill="currentColor" style={style}><path d={d} /></svg>
);
const ArrowUpIcon = (p: { style?: React.CSSProperties }) => <Ic d="M7 14l5-5 5 5z" {...p} />;
const ArrowDownIcon = (p: { style?: React.CSSProperties }) => <Ic d="M7 10l5 5 5-5z" {...p} />;
const DownloadIcon = (p: { style?: React.CSSProperties }) => <Ic d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z" {...p} />;
const ThunderboltIcon = (p: { style?: React.CSSProperties }) => <Ic d="M7 2v11h3v9l7-12h-4l4-8z" {...p} />;

interface AnomalyRow {
  name: string;
  location: string;
  floor: string;
  category: string;
  baseRate: number;
  compareRate: number;
  diff: number;
  key: string;
}

const anomalyColumns = [
  {
    dataIndex: "name",
    key: "name",
    title: "商户",
    render: (_value: string, row: AnomalyRow) => (
      <span style={{ fontWeight: 600 }}>
        {row.name}{" "}
        <span style={{ color: "#999", fontSize: 12 }}>({row.location})</span>
      </span>
    ),
  },
  { dataIndex: "floor", key: "floor", title: "楼层", minWidth: 60 },
  { dataIndex: "category", key: "category", title: "业态", minWidth: 80 },
  {
    dataIndex: "baseRate",
    key: "baseRate",
    title: "基期到岗率",
    minWidth: 100,
    render: (_value: number, row: AnomalyRow) => <Tag color="blue">{row.baseRate}%</Tag>,
    sorter: (a: AnomalyRow, b: AnomalyRow) => a.baseRate - b.baseRate,
  },
  {
    dataIndex: "compareRate",
    key: "compareRate",
    title: "对比期到岗率",
    minWidth: 100,
    render: (_value: number, row: AnomalyRow) => <Tag color="orange">{row.compareRate}%</Tag>,
    sorter: (a: AnomalyRow, b: AnomalyRow) => a.compareRate - b.compareRate,
  },
  {
    dataIndex: "diff",
    key: "diff",
    title: "差异",
    minWidth: 70,
    render: (_value: number, row: AnomalyRow) => (
      <Tag color={row.diff >= 0 ? "green" : "red"}>
        {row.diff >= 0 ? "+" : ""}{row.diff}%
      </Tag>
    ),
    sorter: (a: AnomalyRow, b: AnomalyRow) => a.diff - b.diff,
    defaultSortOrder: "descend" as const,
  },
  {
    key: "trend",
    title: "趋势",
    minWidth: 70,
    render: (_value: unknown, row: AnomalyRow) =>
      row.diff > 0 ? (
        <span style={{ color: "#52c41a" }}>
          <ArrowUpIcon style={{ width: 12, height: 12 }} /> 上升
        </span>
      ) : (
        <span style={{ color: "#ff4d4f" }}>
          <ArrowDownIcon style={{ width: 12, height: 12 }} /> 下降
        </span>
      ),
  },
];

type Period = "daily" | "weekly" | "monthly" | "quarterly" | "yearly";

interface PeriodRange {
  start: Dayjs;
  end: Dayjs;
  label: string;
}

// 根据粒度 + 选中日期，计算周期起止
function getPeriodRange(period: Period, date: Dayjs): PeriodRange {
  switch (period) {
    case "daily":
      return { start: date.startOf("day"), end: date.endOf("day"), label: date.format("YYYY-MM-DD") };
    case "weekly": {
      const start = date.startOf("week");
      return { start, end: start.add(6, "day").endOf("day"), label: `${start.format("MM-DD")} 周` };
    }
    case "monthly":
      return { start: date.startOf("month"), end: date.endOf("month"), label: date.format("YYYY年MM月") };
    case "quarterly": {
      const month = date.month();
      const qStartMonth = Math.floor(month / 3) * 3;
      const start = date.month(qStartMonth).startOf("month");
      const end = start.add(2, "month").endOf("month");
      return { start, end, label: `${date.year()}年Q${Math.floor(month / 3) + 1}` };
    }
    case "yearly":
      return { start: date.startOf("year"), end: date.endOf("year"), label: `${date.year()}年` };
  }
}

// 将周期切分为多个子区间
function splitSubIntervals(period: Period, range: PeriodRange): { start: Dayjs; end: Dayjs; label: string }[] {
  const { start, end } = range;
  const list: { start: Dayjs; end: Dayjs; label: string }[] = [];
  if (period === "daily") {
    list.push({ start, end, label: "当日" });
  } else if (period === "weekly") {
    for (let i = 0; i < 7; i++) {
      const d = start.add(i, "day");
      list.push({ start: d.startOf("day"), end: d.endOf("day"), label: `第${i + 1}天` });
    }
  } else if (period === "monthly") {
    const days = end.date();
    for (let i = 0; i < days; i++) {
      const d = start.add(i, "day");
      list.push({ start: d.startOf("day"), end: d.endOf("day"), label: `${i + 1}日` });
    }
  } else if (period === "quarterly") {
    for (let i = 0; i < 3; i++) {
      const d = start.add(i, "month");
      list.push({ start: d.startOf("month"), end: d.endOf("month"), label: `第${i + 1}月` });
    }
  } else {
    for (let i = 0; i < 12; i++) {
      const d = start.add(i, "month");
      list.push({ start: d.startOf("month"), end: d.endOf("month"), label: `${i + 1}月` });
    }
  }
  return list;
}

function calcRate(records: { status: string }[]): number {
  if (records.length === 0) return 0;
  const signed = records.filter((r) => r.status === "signedIn").length;
  return Math.round((signed / records.length) * 100);
}

const PERIOD_OPTIONS: { label: string; value: Period }[] = [
  { label: "日", value: "daily" },
  { label: "周", value: "weekly" },
  { label: "月", value: "monthly" },
  { label: "季", value: "quarterly" },
  { label: "年", value: "yearly" },
];

const DATE_MODE_MAP: Record<Period, "date" | "month" | "year"> = {
  daily: "date",
  weekly: "date",
  monthly: "month",
  quarterly: "month",
  yearly: "year",
};

interface AnomalyRow {
  key: string;
  name: string;
  floor: string;
  location: string;
  category: string;
  baseRate: number;
  compareRate: number;
  diff: number;
  baseDays: number;
  compareDays: number;
}

export default function Analysis() {
  const { merchants, records } = useAdminStore();

  const [period, setPeriod] = useState<Period>("monthly");
  // 默认基期 = 数据中最新日期所在月，对比期 = 上月
  const latestDate = useMemo(() => {
    if (records.length === 0) return dayjs();
    return records.reduce(
      (max, r) => (dayjs(r.date).isAfter(max) ? dayjs(r.date) : max),
      dayjs(records[0].date)
    );
  }, [records]);

  const [baseDate, setBaseDate] = useState<Dayjs>(latestDate);
  const [compareDate, setCompareDate] = useState<Dayjs>(
    latestDate.subtract(1, "month")
  );
  const [generated, setGenerated] = useState(true);

  const baseRange = useMemo(
    () => getPeriodRange(period, baseDate),
    [period, baseDate]
  );
  const compareRange = useMemo(
    () => getPeriodRange(period, compareDate),
    [period, compareDate]
  );

  // 区间内记录
  const baseRecords = useMemo(
    () =>
      records.filter((r) => {
        const d = dayjs(r.date);
        return (
          (d.isAfter(baseRange.start, "day") || d.isSame(baseRange.start, "day")) &&
          (d.isBefore(baseRange.end, "day") || d.isSame(baseRange.end, "day"))
        );
      }),
    [records, baseRange]
  );
  const compareRecords = useMemo(
    () =>
      records.filter((r) => {
        const d = dayjs(r.date);
        return (
          (d.isAfter(compareRange.start, "day") || d.isSame(compareRange.start, "day")) &&
          (d.isBefore(compareRange.end, "day") || d.isSame(compareRange.end, "day"))
        );
      }),
    [records, compareRange]
  );

  const baseRate = calcRate(baseRecords);
  const compareRate = calcRate(compareRecords);
  const diff = baseRate - compareRate;
  const growth = compareRate !== 0 ? Math.round((diff / compareRate) * 1000) / 10 : 0;

  // 判断同比 / 环比
  const compareLabel = useMemo(() => {
    const yearDiff = baseRange.start.year() - compareRange.start.year();
    if (yearDiff === 1 && baseRange.start.month() === compareRange.start.month()) {
      return "同比";
    }
    if (yearDiff === 0) {
      const monthDiff = baseRange.start.month() - compareRange.start.month();
      if (period === "monthly" && monthDiff === 1) return "环比";
      if (period === "quarterly" && monthDiff === 3) return "环比";
    }
    if (period === "yearly" && yearDiff === 1) return "同比";
    if (period === "daily" && baseRange.start.diff(compareRange.start, "day") === 1) return "环比";
    if (period === "weekly" && baseRange.start.diff(compareRange.start, "week") === 1) return "环比";
    return "对比";
  }, [period, baseRange, compareRange]);

  // 趋势对比
  const trendData = useMemo(() => {
    const baseIntervals = splitSubIntervals(period, baseRange);
    const compareIntervals = splitSubIntervals(period, compareRange);
    const len = Math.max(baseIntervals.length, compareIntervals.length);
    return Array.from({ length: len }, (_, i) => {
      const b = baseIntervals[i];
      const c = compareIntervals[i];
      const bRate = b
        ? calcRate(
            records.filter((r) => {
              const d = dayjs(r.date);
              return (
                (d.isAfter(b.start, "day") || d.isSame(b.start, "day")) &&
                (d.isBefore(b.end, "day") || d.isSame(b.end, "day"))
              );
            })
          )
        : null;
      const cRate = c
        ? calcRate(
            records.filter((r) => {
              const d = dayjs(r.date);
              return (
                (d.isAfter(c.start, "day") || d.isSame(c.start, "day")) &&
                (d.isBefore(c.end, "day") || d.isSame(c.end, "day"))
              );
            })
          )
        : null;
      return {
        label: b?.label ?? c?.label ?? `第${i + 1}段`,
        基期: bRate,
        对比期: cRate,
      };
    });
  }, [records, period, baseRange, compareRange]);

  // 楼层对比
  const floorCompare = useMemo(() => {
    return ["1F", "2F", "3F", "4F"].map((floor) => {
      const floorMerchants = merchants.filter((m) => m.floor === floor);
      const ids = new Set(floorMerchants.map((m) => m.id));
      const bRecs = baseRecords.filter((r) => ids.has(r.merchantId));
      const cRecs = compareRecords.filter((r) => ids.has(r.merchantId));
      return {
        楼层: floor,
        基期: calcRate(bRecs),
        对比期: calcRate(cRecs),
      };
    });
  }, [merchants, baseRecords, compareRecords]);

  // 异常商户：到岗率差异 > 10%
  const anomalyList = useMemo<AnomalyRow[]>(() => {
    return merchants
      .map((m) => {
        const bRecs = baseRecords.filter((r) => r.merchantId === m.id);
        const cRecs = compareRecords.filter((r) => r.merchantId === m.id);
        const bRate = calcRate(bRecs);
        const cRate = calcRate(cRecs);
        const d = bRate - cRate;
        return {
          key: m.id,
          name: m.name,
          floor: m.floor,
          location: m.location,
          category: m.category,
          baseRate: bRate,
          compareRate: cRate,
          diff: d,
          baseDays: bRecs.length,
          compareDays: cRecs.length,
        };
      })
      .filter((m) => m.baseDays > 0 && m.compareDays > 0 && Math.abs(m.diff) > 10)
      .sort((a, b) => Math.abs(b.diff) - Math.abs(a.diff));
  }, [merchants, baseRecords, compareRecords]);

  const handleGenerate = () => {
    setGenerated(true);
    Message.success("分析已生成");
  };

  const handleExport = () => {
    if (anomalyList.length === 0) {
      Message.warning("暂无异常数据可导出");
      return;
    }
    exportCsv(
      anomalyList.map((m) => ({
        商户名称: m.name,
        楼层: m.floor,
        铺位: m.location,
        业态: m.category,
        基期到岗率: `${m.baseRate}%`,
        对比期到岗率: `${m.compareRate}%`,
        差异: `${m.diff}%`,
        趋势: m.diff > 0 ? "上升" : "下降",
      })),
      `考勤异常分析_${baseRange.label}_vs_${compareRange.label}`
    );
  };

  // 根据当前周期粒度渲染对应 DatePicker（Arco 通过子组件切换月/年）
  const renderDatePicker = (
    currentValue: Dayjs,
    onSelect: (val: string) => void
  ): React.ReactNode => {
    const mode = DATE_MODE_MAP[period];
    const size = "small";
    if (mode === "month") {
      return (
        <DatePicker.MonthPicker
          value={currentValue.toDate()}
          onChange={onSelect}
          size={size}
        />
      );
    }
    if (mode === "year") {
      return (
        <DatePicker.YearPicker
          value={currentValue.toDate()}
          onChange={onSelect}
          size={size}
        />
      );
    }
    return (
      <DatePicker
        value={currentValue.toDate()}
        onChange={onSelect}
        size={size}
      />
    );
  };

  return (
    <div>
      {/* 控制区 */}
      <Card title="考勤深度分析（同比 / 环比）" bordered>
        <div className="filter-bar">
          <Radio.Group
            value={period}
            onChange={(value: Period) => {
              setPeriod(value);
              setGenerated(false);
            }}
            type="button"
            size="small"
          >
            {PERIOD_OPTIONS.map((o) => (
              <Radio key={o.value} value={o.value}>
                {o.label}
              </Radio>
            ))}
          </Radio.Group>
          <div className="inline-group" style={{ gap: 6 }}>
            <span style={{ color: "#999" }}>基期：</span>
            {renderDatePicker(baseDate, (val: string) => {
              if (val) {
                setBaseDate(dayjs(val));
                setGenerated(false);
              }
            })}
          </div>
          <div className="inline-group" style={{ gap: 6 }}>
            <span style={{ color: "#999" }}>对比期：</span>
            {renderDatePicker(compareDate, (val: string) => {
              if (val) {
                setCompareDate(dayjs(val));
                setGenerated(false);
              }
            })}
          </div>
          <Button
            type="primary"
            icon={<ThunderboltIcon />}
            onClick={handleGenerate}
          >
            生成分析
          </Button>
        </div>
      </Card>

      {!generated ? (
        <Card style={{ marginTop: 16 }}>
          <div style={{ textAlign: "center", padding: 40, color: "#999" }}>
            请选择周期与日期后点击「生成分析」
          </div>
        </Card>
      ) : (
        <>
          {/* 汇总卡 */}
          <div className="stat-grid" style={{ marginTop: 16 }}>
            <Card bordered bodyStyle={{ display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", minHeight: 100 }}>
              <Statistic title="基期到岗率" value={baseRate} suffix="%" styleValue={{ color: "#1677ff" }} />
              <span style={{ color: "#999", fontSize: 12 }}>{baseRange.label}</span>
            </Card>
            <Card bordered bodyStyle={{ display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", minHeight: 100 }}>
              <Statistic title="对比期到岗率" value={compareRate} suffix="%" styleValue={{ color: "#8c8c8c" }} />
              <span style={{ color: "#999", fontSize: 12 }}>{compareRange.label}</span>
            </Card>
            <Card bordered bodyStyle={{ display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", minHeight: 100 }}>
              <Statistic
                title={`${compareLabel}差异`}
                value={diff}
                suffix="%"
                styleValue={{ color: diff >= 0 ? "#52c41a" : "#ff4d4f" }}
                prefix={diff >= 0 ? <ArrowUpIcon /> : <ArrowDownIcon />}
              />
              <span style={{ color: "#999", fontSize: 12 }}>基期 − 对比期</span>
            </Card>
            <Card bordered bodyStyle={{ display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", minHeight: 100 }}>
              <Statistic
                title="增长率"
                value={growth}
                suffix="%"
                styleValue={{ color: growth >= 0 ? "#52c41a" : "#ff4d4f" }}
                prefix={growth >= 0 ? <ArrowUpIcon /> : <ArrowDownIcon />}
              />
              <span style={{ color: "#999", fontSize: 12 }}>相对对比期</span>
            </Card>
          </div>

          {/* 趋势对比 */}
          <Card title="趋势对比" style={{ marginTop: 16 }} bordered>
            <div className="chart-container" style={{ height: 320 }}>
              <VChartComponent spec={{
                type: 'common',
                data: [{ id: 'trend', values: trendData }],
                series: [
                  { type: 'line', xField: 'label', yField: '基期', point: { visible: true }, line: { style: { stroke: '#1677ff', lineWidth: 2 } }, seriesField: '基期' },
                  { type: 'line', xField: 'label', yField: '对比期', point: { visible: true }, line: { style: { stroke: '#fa8c16', lineWidth: 2, lineDash: [5, 3] } }, seriesField: '对比期' }
                ],
                axes: [
                  { orient: 'bottom', label: { visible: true } },
                  { orient: 'left', label: { visible: true }, min: 0, max: 100 }
                ],
                tooltip: { mark: { visible: true } },
                legends: { visible: true }
              } as any} />
            </div>
          </Card>

          {/* 楼层对比 */}
          <Card title="各楼层到岗率对比" style={{ marginTop: 16 }} bordered>
            <div className="chart-container" style={{ height: 320 }}>
              <VChartComponent spec={{
                type: 'common',
                data: [{ id: 'floor', values: floorCompare }],
                series: [
                  { type: 'bar', xField: '楼层', yField: '基期', bar: { style: { fill: '#1677ff', cornerRadius: [4, 4, 0, 0] } }, seriesField: '基期' },
                  { type: 'bar', xField: '楼层', yField: '对比期', bar: { style: { fill: '#fa8c16', cornerRadius: [4, 4, 0, 0] } }, seriesField: '对比期' }
                ],
                axes: [
                  { orient: 'bottom', label: { visible: true } },
                  { orient: 'left', label: { visible: true }, min: 0, max: 100 }
                ],
                tooltip: { mark: { visible: true } },
                legends: { visible: true }
              } as any} />
            </div>
          </Card>

          {/* 异常表 */}
          <Card
            style={{ marginTop: 16 }}
            bordered
          >
            <div className="card-section-header">
              <span className="card-title-text">异常商户明细（到岗率差异 &gt; 10%）</span>
              <div className="card-actions">
                <Button
                  icon={<DownloadIcon />}
                  onClick={handleExport}
                  size="small"
                >
                  导出 CSV
                </Button>
              </div>
            </div>
            <div className="table-wrap">
              <Table
                data={anomalyList}
                rowKey="key"
                size="small"
                border={{ wrapper: true, cell: true }}
                scroll={{ x: "max-content" }}
                pagination={{ pageSize: 10, showTotal: true, sizeCanChange: false }}
                columns={anomalyColumns}
              />
            </div>
          </Card>
        </>
      )}
    </div>
  );
}
