// src/views/reports/index.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { Message } from '@arco-design/web-vue';
import type { TableColumnData } from '@arco-design/web-vue';
import dayjs from 'dayjs';
import { useAdminStore } from '@/store/admin';
import { exportCsv } from '@/utils/exportCsv';
import VChartView from '@/components/VChartView.vue';
import type { AttendanceRecord, Merchant } from '@/types';

const store = useAdminStore();

onMounted(() => {
  if (!store.merchants.length || !store.records.length) {
    store.loadFromApi();
  }
});

// ===== 周期与日期范围 =====
type PeriodType = 'week' | 'month' | 'quarter' | 'custom';
const periodType = ref<PeriodType>('month');
const dateRange = ref<string[]>([
  dayjs().startOf('month').format('YYYY-MM-DD'),
  dayjs().endOf('month').format('YYYY-MM-DD'),
]);

const periodOptions = [
  { label: '周', value: 'week' },
  { label: '月', value: 'month' },
  { label: '季', value: 'quarter' },
  { label: '自定义', value: 'custom' },
];

function quarterStart(d: dayjs.Dayjs): dayjs.Dayjs {
  const qStart = Math.floor(d.month() / 3) * 3;
  return d.month(qStart).startOf('month');
}

watch(periodType, (t) => {
  const today = dayjs();
  let s: dayjs.Dayjs;
  let e: dayjs.Dayjs;
  switch (t) {
    case 'week':
      s = today.startOf('week');
      e = today.endOf('week');
      break;
    case 'month':
      s = today.startOf('month');
      e = today.endOf('month');
      break;
    case 'quarter':
      s = quarterStart(today);
      e = s.add(2, 'month').endOf('month');
      break;
    default:
      return; // 自定义：保留用户当前选择
  }
  dateRange.value = [s.format('YYYY-MM-DD'), e.format('YYYY-MM-DD')];
});

const start = computed(() => dateRange.value?.[0] ?? '');
const end = computed(() => dateRange.value?.[1] ?? '');

const rangeRecords = computed<AttendanceRecord[]>(() => {
  if (!start.value || !end.value) return [];
  return store.records.filter((r) => r.date >= start.value && r.date <= end.value);
});

// ===== 统计卡 =====
const stats = computed(() => {
  const recs = rangeRecords.value;
  const dates = new Set(recs.map((r) => r.date));
  const signedIn = recs.filter((r) => r.status === 'signedIn').length;
  const absent = recs.filter((r) => r.status === 'absent').length;
  const rate = recs.length > 0 ? Math.round((signedIn / recs.length) * 1000) / 10 : 0;
  return { days: dates.size, signedIn, absent, rate };
});

// ===== 每日考勤趋势线图 =====
const trendSpec = computed(() => {
  const byDate = new Map<string, { signedIn: number; absent: number; unsigned: number }>();
  rangeRecords.value.forEach((r) => {
    const d = byDate.get(r.date) ?? { signedIn: 0, absent: 0, unsigned: 0 };
    if (r.status === 'signedIn') d.signedIn++;
    else if (r.status === 'absent') d.absent++;
    else d.unsigned++;
    byDate.set(r.date, d);
  });
  const dates = Array.from(byDate.keys()).sort();
  const values: { date: string; type: string; value: number }[] = [];
  dates.forEach((d) => {
    const item = byDate.get(d)!;
    const label = dayjs(d).format('MM/DD');
    values.push({ date: label, type: '已到岗', value: item.signedIn });
    values.push({ date: label, type: '缺勤', value: item.absent });
    values.push({ date: label, type: '未签到', value: item.unsigned });
  });
  return {
    type: 'line',
    data: [{ id: 'trend', values }],
    series: [
      { type: 'line', xField: 'date', yField: 'value', seriesField: 'type', point: { visible: true }, line: { style: { lineWidth: 2 } } },
    ],
    axes: [
      { orient: 'bottom', type: 'band' },
      { orient: 'left', type: 'linear' },
    ],
    legends: { visible: true, position: 'top' },
    tooltip: { visible: true },
  };
});

// ===== 楼层考勤对比柱图 =====
const floorSpec = computed(() => {
  const floors = Array.from(new Set(store.merchants.map((m) => m.floor))).filter(Boolean).sort();
  const values: { floor: string; type: string; value: number }[] = [];
  floors.forEach((f) => {
    const mids = store.merchants.filter((m) => m.floor === f).map((m) => m.id);
    const recs = rangeRecords.value.filter((r) => mids.includes(r.merchantId));
    const signedIn = recs.filter((r) => r.status === 'signedIn').length;
    const absent = recs.filter((r) => r.status === 'absent').length;
    values.push({ floor: f, type: '已到岗', value: signedIn });
    values.push({ floor: f, type: '缺勤', value: absent });
  });
  return {
    type: 'bar',
    data: [{ id: 'floor', values }],
    series: [{ type: 'bar', xField: 'floor', yField: 'value', seriesField: 'type' }],
    axes: [
      { orient: 'bottom', type: 'band' },
      { orient: 'left', type: 'linear' },
    ],
    legends: { visible: true, position: 'top' },
    tooltip: { visible: true },
  };
});

// ===== 商户考勤明细表 =====
interface MerchantRow {
  merchantId: string;
  name: string;
  floor: string;
  expected: number;
  signedIn: number;
  absent: number;
  rate: number;
  status: string;
}

const merchantRows = computed<MerchantRow[]>(() => {
  return store.merchants
    .map((m: Merchant) => {
      const recs = rangeRecords.value.filter((r) => r.merchantId === m.id);
      const signedIn = recs.filter((r) => r.status === 'signedIn').length;
      const absent = recs.filter((r) => r.status === 'absent').length;
      const rate = recs.length > 0 ? Math.round((signedIn / recs.length) * 1000) / 10 : 0;
      const status = m.signedIn ? 'signedIn' : m.absent ? 'absent' : 'unsigned';
      return {
        merchantId: m.id,
        name: m.name,
        floor: m.floor,
        expected: recs.length,
        signedIn,
        absent,
        rate,
        status,
      };
    })
    .filter((r) => r.expected > 0)
    .sort((a, b) => b.rate - a.rate);
});

function statusText(s: string) {
  return s === 'signedIn' ? '已到岗' : s === 'absent' ? '缺勤' : '未签到';
}
function statusColor(s: string) {
  return s === 'signedIn' ? 'green' : s === 'absent' ? 'red' : '';
}

const columns: TableColumnData[] = [
  { title: '商户', dataIndex: 'name' },
  { title: '楼层', dataIndex: 'floor', width: 80, align: 'center' },
  { title: '应到', dataIndex: 'expected', width: 90, align: 'right', sortable: { sortDirections: ['descend', 'ascend'], sorter: (a, b) => a.expected - b.expected } },
  { title: '实到', dataIndex: 'signedIn', width: 90, align: 'right', sortable: { sortDirections: ['descend', 'ascend'], sorter: (a, b) => a.signedIn - b.signedIn } },
  { title: '缺勤', dataIndex: 'absent', width: 90, align: 'right', sortable: { sortDirections: ['descend', 'ascend'], sorter: (a, b) => a.absent - b.absent } },
  { title: '到岗率', slotName: 'rate', width: 200, sortable: { sortDirections: ['descend', 'ascend'], sorter: (a, b) => a.rate - b.rate } },
  { title: '状态', slotName: 'status', width: 100, align: 'center' },
];

function handleExport() {
  if (!merchantRows.value.length) {
    Message.warning('暂无可导出的数据');
    return;
  }
  exportCsv(
    `报表统计-${start.value}_${end.value}`,
    merchantRows.value.map((r) => ({
      商户: r.name,
      楼层: r.floor,
      应到: r.expected,
      实到: r.signedIn,
      缺勤: r.absent,
      到岗率: r.rate,
      状态: statusText(r.status),
    }))
  );
  Message.success('已导出');
}
</script>

<template>
  <div class="page-container">
    <!-- 顶部：周期 + 日期范围 -->
    <a-card style="margin-bottom: 16px">
      <div class="toolbar">
        <a-space wrap :size="12">
          <span class="control-label">周期</span>
          <a-radio-group v-model="periodType" type="button" size="small">
            <a-radio v-for="o in periodOptions" :key="o.value" :value="o.value">{{ o.label }}</a-radio>
          </a-radio-group>
          <a-range-picker
            v-model="dateRange"
            value-format="YYYY-MM-DD"
            format="YYYY-MM-DD"
            style="width: 280px"
            :placeholder="['开始日期', '结束日期']"
          />
        </a-space>
        <a-button type="primary" @click="handleExport">
          <template #icon><icon-download /></template>
          导出 CSV
        </a-button>
      </div>
    </a-card>

    <!-- 统计卡 -->
    <a-grid :cols="{ xs: 2, sm: 4 }" :col-gap="12" :row-gap="12" style="margin-bottom: 16px">
      <a-grid-item>
        <a-card>
          <div class="stat-card-value">{{ stats.days }}</div>
          <div class="stat-card-label">应到天数</div>
        </a-card>
      </a-grid-item>
      <a-grid-item>
        <a-card>
          <div class="stat-card-value" style="color: rgb(var(--green-6))">{{ stats.signedIn }}</div>
          <div class="stat-card-label">实到人次</div>
        </a-card>
      </a-grid-item>
      <a-grid-item>
        <a-card>
          <div class="stat-card-value" style="color: rgb(var(--red-6))">{{ stats.absent }}</div>
          <div class="stat-card-label">缺勤人次</div>
        </a-card>
      </a-grid-item>
      <a-grid-item>
        <a-card>
          <div class="stat-card-value" style="color: rgb(var(--primary-6))">{{ stats.rate }}%</div>
          <div class="stat-card-label">平均到岗率</div>
        </a-card>
      </a-grid-item>
    </a-grid>

    <!-- 图表区 -->
    <a-grid :cols="{ xs: 1, lg: 2 }" :col-gap="12" :row-gap="12" style="margin-bottom: 16px">
      <a-grid-item>
        <a-card title="每日考勤趋势">
          <div style="height: 320px"><VChartView :spec="trendSpec" /></div>
        </a-card>
      </a-grid-item>
      <a-grid-item>
        <a-card title="楼层考勤对比">
          <div style="height: 320px"><VChartView :spec="floorSpec" /></div>
        </a-card>
      </a-grid-item>
    </a-grid>

    <!-- 商户考勤明细表 -->
    <a-card title="商户考勤明细">
      <a-table
        :data="merchantRows"
        :columns="columns"
        :pagination="{ pageSize: 15, showTotal: true }"
        :loading="store.loading"
        row-key="merchantId"
        size="medium"
        :scroll="{ x: 800 }"
      >
        <template #rate="{ record }">
          <a-progress :percent="record.rate" size="small" />
        </template>
        <template #status="{ record }">
          <a-tag :color="statusColor(record.status)">{{ statusText(record.status) }}</a-tag>
        </template>
      </a-table>
    </a-card>
  </div>
</template>

<style scoped>
.toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 12px;
}
.control-label {
  color: var(--color-text-3);
  font-size: 13px;
}
</style>

// src/pages/admin/Reports.tsx
import { useMemo, useState, useEffect, useRef } from "react";
import {
  Card,
  DatePicker,
  Radio,
  Table,
  Tag,
  Button,
} from "@arco-design/web-react";
import { IconDownload } from "@arco-design/web-react/icon";
import dayjs from "dayjs";
import VChart from "@visactor/vchart";
import { useAdminStore } from "@/store/useAdminStore";
import { exportCsv } from "@/utils/exportCsv";

/* VChart 图表组件 */
function VChartComponent({ spec }: { spec: any }) {
  const divRef = useRef<HTMLDivElement>(null);
  const chartRef = useRef<any>(null);

  useEffect(() => {
    if (!divRef.current) return;
    const chart = new VChart(spec, { dom: divRef.current });
    chartRef.current = chart;
    chart.renderSync();
    return () => {
      chartRef.current?.release();
      chartRef.current = null;
    };
  }, [JSON.stringify(spec)]);

  return <div ref={divRef} style={{ width: "100%", height: "100%" }} />;
}

type Period = "week" | "month" | "quarter" | "custom";

export default function Reports() {
  const { merchants, records } = useAdminStore();
  const [period, setPeriod] = useState<Period>("week");
  const [customRange, setCustomRange] = useState<[string, string]>([
    dayjs().subtract(29, "day").format("YYYY-MM-DD"),
    dayjs().format("YYYY-MM-DD"),
  ]);

  const dateRange = useMemo(() => {
    const end = dayjs();
    switch (period) {
      case "week":
        return [end.subtract(6, "day"), end];
      case "month":
        return [end.subtract(29, "day"), end];
      case "quarter":
        return [end.subtract(89, "day"), end];
      case "custom":
        return [dayjs(customRange[0]), dayjs(customRange[1])];
    }
  }, [period, customRange]);

  const rangeRecords = useMemo(() => {
    return records.filter((r) => {
      const d = dayjs(r.date);
      return (
        (d.isAfter(dateRange[0], "day") || d.isSame(dateRange[0], "day")) &&
        (d.isBefore(dateRange[1], "day") || d.isSame(dateRange[1], "day"))
      );
    });
  }, [records, dateRange]);

  // 总体统计
  const total = rangeRecords.length;
  const signedIn = rangeRecords.filter((r) => r.status === "signedIn").length;
  const absent = rangeRecords.filter((r) => r.status === "absent").length;
  const unsigned = rangeRecords.filter((r) => r.status === "unsigned").length;
  const rate = total ? Math.round((signedIn / total) * 100) : 0;

  // 每日趋势
  const trendData = useMemo(() => {
    const map: Record<string, { signed: number; absent: number; unsigned: number }> = {};
    rangeRecords.forEach((r) => {
      if (!map[r.date]) {
        map[r.date] = { signed: 0, absent: 0, unsigned: 0 };
      }
      if (r.status === "signedIn") map[r.date].signed++;
      else if (r.status === "absent") map[r.date].absent++;
      else map[r.date].unsigned++;
    });
    return Object.keys(map)
      .sort()
      .map((date) => ({
        date: date.slice(5),
        到岗: map[date].signed,
        缺勤: map[date].absent,
        未签到: map[date].unsigned,
        到岗率:
          map[date].signed + map[date].absent + map[date].unsigned > 0
            ? Math.round(
                (map[date].signed /
                  (map[date].signed + map[date].absent + map[date].unsigned)) *
                  100
              )
            : 0,
      }));
  }, [rangeRecords]);

  // 各楼层统计
  const floorData = useMemo(() => {
    return ["1F", "2F", "3F", "4F"].map((floor) => {
      const floorMerchants = merchants.filter((m) => m.floor === floor);
      const floorRecords = rangeRecords.filter((r) =>
        floorMerchants.some((m) => m.id === r.merchantId)
      );
      const signed = floorRecords.filter((r) => r.status === "signedIn").length;
      const abs = floorRecords.filter((r) => r.status === "absent").length;
      const uns = floorRecords.filter((r) => r.status === "unsigned").length;
      return {
        楼层: floor,
        到岗: signed,
        缺勤: abs,
        未签到: uns,
        到岗率: floorRecords.length
          ? Math.round((signed / floorRecords.length) * 100)
          : 0,
      };
    });
  }, [merchants, rangeRecords]);

  // 商户维度排行
  const merchantStats = useMemo(() => {
    return merchants
      .map((m) => {
        const list = rangeRecords.filter((r) => r.merchantId === m.id);
        const signed = list.filter((r) => r.status === "signedIn").length;
        const absent = list.filter((r) => r.status === "absent").length;
        const unsigned = list.filter((r) => r.status === "unsigned").length;
        return {
          key: m.id,
          id: m.id,
          name: m.name,
          floor: m.floor,
          location: m.location,
          category: m.category,
          signed,
          absent,
          unsigned,
          total: list.length,
          rate: list.length ? Math.round((signed / list.length) * 100) : 0,
        };
      })
      .sort((a, b) => b.rate - a.rate);
  }, [merchants, rangeRecords]);

  const handleExport = () => {
    exportCsv(
      merchantStats.map((m) => ({
        商户名称: m.name,
        楼层: m.floor,
        铺位: m.location,
        业态: m.category,
        应到天数: m.total,
        已到岗: m.signed,
        缺勤: m.absent,
        未签到: m.unsigned,
        到岗率: `${m.rate}%`,
      })),
      `考勤报表_${dateRange[0].format("YYYYMMDD")}-${dateRange[1].format(
        "YYYYMMDD"
      )}`
    );
  };

  const statItems = [
    { title: "记录总数", value: total, color: undefined },
    { title: "到岗", value: signedIn, color: "rgb(var(--primary-6))" },
    { title: "缺勤", value: absent, color: "rgb(var(--danger-6))" },
    { title: "到岗率", value: rate, color: "rgb(var(--primary-6))", suffix: "%" },
  ];

  return (
    <div>
      <Card
        title={
          <div className="card-header-bar">
            <span className="card-title-text">考勤报表统计</span>
          </div>
        }
        bordered
      >
        <div className="filter-bar">
          <Radio.Group
            value={period}
            onChange={(value: Period) => setPeriod(value)}
            type="button"
            size="small"
          >
            <Radio value="week">近7天</Radio>
            <Radio value="month">近30天</Radio>
            <Radio value="quarter">近90天</Radio>
            <Radio value="custom">自定义</Radio>
          </Radio.Group>
          {period === "custom" && (
            <DatePicker.RangePicker
              value={customRange}
              onChange={(dateString: string[]) => {
                if (dateString && dateString[0] && dateString[1]) {
                  setCustomRange([dateString[0], dateString[1]]);
                }
              }}
              format="YYYY-MM-DD"
            />
          )}
          <Button
            type="primary"
            icon={<IconDownload />}
            onClick={handleExport}
          >
            导出 CSV
          </Button>
        </div>

        <div className="stat-grid">
          {statItems.map((item) => (
            <Card key={item.title} bordered>
              <div style={{ textAlign: "center" }}>
                <div style={{ fontSize: 13, color: "#999", marginBottom: 4 }}>
                  {item.title}
                </div>
                <div style={{ fontSize: 28, fontWeight: 600, color: item.color ?? "#333" }}>
                  {item.value}
                  {item.suffix && (
                    <span style={{ fontSize: 14 }}>{item.suffix}</span>
                  )}
                </div>
              </div>
            </Card>
          ))}
        </div>
      </Card>

      <Card
        title={
          <div className="card-header-bar">
            <span className="card-title-text">每日考勤趋势</span>
          </div>
        }
        style={{ marginTop: 16 }}
        bordered
      >
        <div className="chart-container" style={{ height: 320 }}>
          <VChartComponent spec={{
            type: 'common',
            data: [{ id: 'trend', values: trendData }],
            series: [
              { type: 'line', xField: 'date', yField: '到岗', point: { visible: true }, line: { style: { stroke: '#16a34a', lineWidth: 2 } }, seriesField: '到岗' },
              { type: 'line', xField: 'date', yField: '缺勤', point: { visible: true }, line: { style: { stroke: '#ef4444', lineWidth: 2 } }, seriesField: '缺勤' },
              { type: 'line', xField: 'date', yField: '未签到', point: { visible: true }, line: { style: { stroke: '#f59e0b', lineWidth: 2 } }, seriesField: '未签到' }
            ],
            axes: [
              { orient: 'bottom', label: { visible: true } },
              { orient: 'left', label: { visible: true } }
            ],
            tooltip: { mark: { visible: true } },
            legends: { visible: true }
          } as any} />
        </div>
      </Card>

      <Card
        title={
          <div className="card-header-bar">
            <span className="card-title-text">楼层考勤对比</span>
          </div>
        }
        style={{ marginTop: 16 }}
        bordered
      >
        <div className="chart-container" style={{ height: 320 }}>
          <VChartComponent spec={{
            type: 'common',
            data: [{ id: 'floor', values: floorData }],
            series: [
              { type: 'bar', xField: '楼层', yField: '到岗', bar: { style: { fill: '#16a34a' } }, seriesField: '到岗' },
              { type: 'bar', xField: '楼层', yField: '缺勤', bar: { style: { fill: '#ef4444' } }, seriesField: '缺勤' },
              { type: 'bar', xField: '楼层', yField: '未签到', bar: { style: { fill: '#f59e0b' } }, seriesField: '未签到' }
            ],
            axes: [
              { orient: 'bottom', label: { visible: true } },
              { orient: 'left', label: { visible: true } }
            ],
            tooltip: { mark: { visible: true } },
            legends: { visible: true }
          } as any} />
        </div>
      </Card>

      <Card
        title={
          <div className="card-header-bar">
            <span className="card-title-text">商户考勤明细</span>
          </div>
        }
        style={{ marginTop: 16 }}
        bordered
      >
        <div style={{ marginBottom: 8 }}>
          <span className="text-secondary">按到岗率排序</span>
        </div>
        <div className="table-wrap">
          <Table
            data={merchantStats}
            rowKey="id"
            size="small"
            border={{ wrapper: true, cell: true }}
            stripe
            hover
            scroll={{ x: "max-content" }}
            pagination={{ pageSize: 10, showTotal: true, sizeCanChange: false }}
            columns={[
              {
                title: "排名",
                key: "rank",
                width: 60,
                render: (_value: unknown, _record: unknown, index: number) => index + 1,
              },
              {
                title: "商户",
                dataIndex: "name",
                key: "name",
                render: (_value: unknown, row: typeof merchantStats[number]) => (
                  <span>
                    <span style={{ fontWeight: 600 }}>{row.name}</span>{" "}
                    <span className="text-secondary">({row.location})</span>
                  </span>
                ),
              },
              { title: "业态", dataIndex: "category", key: "category", minWidth: 80 },
              { title: "应到", dataIndex: "total", key: "total", minWidth: 60 },
              {
                title: "已到岗",
                dataIndex: "signed",
                key: "signed",
                minWidth: 70,
                render: (_value: unknown, row: typeof merchantStats[number]) => (
                  <span style={{ color: "rgb(var(--success-6))" }}>{row.signed}</span>
                ),
              },
              {
                title: "缺勤",
                dataIndex: "absent",
                key: "absent",
                minWidth: 60,
                render: (_value: unknown, row: typeof merchantStats[number]) =>
                  row.absent > 0 ? (
                    <Tag color="red" bordered={false}>{row.absent}</Tag>
                  ) : (
                    <span className="text-secondary">0</span>
                  ),
              },
              {
                title: "未签到",
                dataIndex: "unsigned",
                key: "unsigned",
                minWidth: 70,
                render: (_value: unknown, row: typeof merchantStats[number]) =>
                  row.unsigned > 0 ? (
                    <Tag color="orange" bordered={false}>{row.unsigned}</Tag>
                  ) : (
                    <span className="text-secondary">0</span>
                  ),
              },
              {
                title: "到岗率",
                dataIndex: "rate",
                key: "rate",
                minWidth: 80,
                sorter: (a: typeof merchantStats[number], b: typeof merchantStats[number]) => a.rate - b.rate,
                render: (_value: unknown, row: typeof merchantStats[number]) => (
                  <Tag
                    color={row.rate >= 80 ? "green" : row.rate >= 60 ? "orange" : "red"}
                    bordered={false}
                  >
                    {row.rate}%
                  </Tag>
                ),
              },
            ]}
          />
        </div>
      </Card>
    </div>
  );
}
